version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main1.py
  upload:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: docker tag shanmukh:latest shanmukhsreerangam/project:shanmukh1
      - run: docker push shanmukhsreerangam/project:shanmukh1

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload