version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  build1:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t hari .

      - run:
          name: Push to Docker Hub
          command: |
            docker login -u shanmukhsreerangam -p Shanmukh@0410
            docker tag hari:latest shanmukhsreerangam/project:hari1
            docker push shanmukhsreerangam/project:hari1
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main1.py
  upload:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build1